version: "3.1"
    
services:
  mysql:
    container_name: MQ_${CONTAINER_NAME} 
    image: mysql:5.7
    volumes:
      - ./wordpress/mysql:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1gb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_WP_PASSWORD}
      MYSQL_DATABASE: ${DB_WP_NAME}
      MYSQL_USER: ${MYSQL_WP_USER}
      MYSQL_PASSWORD: ${MYSQL_WP_PASSWORD}
    
  wordpress:
    container_name: WP_${CONTAINER_NAME}
    depends_on:
      - mysql
    image: wordpress:latest
    volumes:
      - ./wordpress/wp:/var/www/html
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1gb
    ports:
      - "${WP_PORT}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${MYSQL_WP_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_WP_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_WP_NAME}
      VIRTUAL_HOST: prueba.com
  
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    environment:
      DEFAULT_HOST: arcux.local
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - red

volumes:
  db_data: {}
  wordpress_data: {}

networks:
  red:
    driver: "bridge"