version: "3.1"
    
services:
  mysql:
    container_name: MYSQL_${CONTAINER_NAME} 
    image: mysql:5.7
    volumes:
      - ./wordpress/mysql:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1gb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_WP_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_WP_DB_NAME}
      MYSQL_USER: ${MYSQL_WP_USER}
      MYSQL_PASSWORD: ${MYSQL_WP_PASSWORD}
    
  wordpress:
    container_name: WP_${CONTAINER_NAME}
    depends_on:
      - mysql
    image: wordpress:latest
    volumes:
      - ./wordpress/wp:/var/www/html
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1gb
    ports:
      - "${WP_PORT}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${MYSQL_WP_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_WP_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_WP_DB_NAME}

volumes:
  db_data: {}
  wordpress_data: {}